imports:
    - { resource: "@SyliusCmsPlugin/config/grids.yaml" }
    - { resource: "@SyliusCmsPlugin/config/services.xml" }
    - { resource: '@SyliusCmsPlugin/config/twig_hooks/**/*.yaml' }

parameters:
    sylius.sitemap.path: "%kernel.project_dir%/var/sitemap"
    sylius_cms_api_platform_mapping_path: '%kernel.project_dir%/vendor/sylius/cms-plugin/config/api_platform/'
    sylius_validation_group: [cms]
    sylius_cms.form.type.block.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.content_configuration.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.block_image.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.page.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.translation.page.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.collection.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.translation.media.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.media.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.template.validation_groups: "%sylius_validation_group%"
    sylius_cms.images_dir: "%kernel.project_dir%/public/media/images"
    sylius_cms.videos_dir: "%kernel.project_dir%/public/media/video"
    sylius_cms.files_dir: "%kernel.project_dir%/public/media/file"

flysystem:
    storages:
        sylius_cms_media.image.storage:
            adapter: 'local'
            options:
                directory: '%sylius_cms.images_dir%'
            directory_visibility: 'public'
        sylius_cms_media.video.storage:
            adapter: 'local'
            options:
                directory: '%sylius_cms.videos_dir%'
            directory_visibility: 'public'
        sylius_cms_media.file.storage:
            adapter: 'local'
            options:
                directory: '%sylius_cms.files_dir%'
            directory_visibility: 'public'

sylius_twig_extra:
    twig_ux:
        anonymous_component_template_prefixes:
            'sylius_cms:shop': "@SyliusCmsPlugin/shop/shared/components"

twig:
    form_themes:
        - '@SyliusCmsPlugin/admin/shared/editor/trix.html.twig'
        - '@SyliusCmsPlugin/admin/shared/editor/jodit.html.twig'

liip_imagine:
    filter_sets:
        sylius_admin_product_original: ~
        sylius_admin_avatar:
            format: webp
            quality: 80
            filters:
                thumbnail: { size: [ 200, 200 ], mode: outbound }
        sylius_admin_product_thumbnail:
            format: webp
            quality: 80
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
        sylius_admin_product_large_thumbnail:
            format: webp
            quality: 80
            filters:
                thumbnail: { size: [600, 800], mode: outbound }
        sylius_original: ~
        sylius_small:
            format: webp
            quality: 80
            filters:
                thumbnail: { size: [ 120, 90 ], mode: outbound }
        sylius_medium:
            format: webp
            quality: 80
            filters:
                thumbnail: { size: [ 240, 180 ], mode: outbound }
        sylius_large:
            format: webp
            quality: 80
            filters:
                thumbnail: { size: [ 640, 480 ], mode: outbound }
