sylius_grid:
    grids:
        sylius_admin_locale:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.locale.class%"
            sorting:
                code: asc
            fields:
                name:
                    type: twig
                    label: sylius_cms.ui.name
                    sortable: name
                    path: .
                    options:
                        template: "@SyliusCmsPlugin/admin/grid/field/name.html.twig"
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusBootstrapAdminUi/shared/grid/field/boolean.html.twig"
            filters:
                code:
                    type: string
                    label: sylius.ui.code
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create
